version: "3"
networks:
  nem_financial:
    external: false

services:
  nem_financial_app:
    networks:
      - nem_financial
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      ENV_NAME: dev
  database:
    image: mariadb
    ports:
     - 3306:3306
    expose:
     - 3306
    volumes:
     - ./docker/mariadb/data:/var/lib/mysql:rw
     - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
